### ISSUE TITLE
Add `tmp` dir to the .npmignore. 

### ISSUE THREAD

**Issue by ChALkeR** [rwwagner90/ember-shepherd#15]
*Disclaimer: I do not use the package, this was found during automated npm packages downloading.*

Your current package size is 107 MiB packed, 622 MiB unpacked. 621 MiB of that are inside the `tmp` dir. I think that this probably got packed to the release by mistake.

Btw: you also packed your `.idea` dir to the release.

**Comment by ChALkeR** [comment]
Very similar to https://github.com/srsgores/ember-accessible-icon/issues/2

**Comment by ChALkeR** [comment]
Common issue: https://github.com/emberjs/ember.js/issues/11316

**Comment by rwwagner90** [comment]
@ChALkeR sounds like maybe Ember needs to add tmp to the default .npmignore that is generated?

**Comment by ChALkeR** [comment]
@rwwagner90 Because that's a common problem, I already filed an issue on `emberjs` itself.
You can propose your methods of fixing it there. I do not use `emberjs` myself, so I don't know.

But if the package, the initial structure, or the '.npmignore` is generated by the `emberjs` itself, then adding such directories to the default `.npmignore` should fix the issue for the new packages IMO.

**Comment by ChALkeR** [comment]
Moved common issue: https://github.com/ember-cli/ember-cli/issues/4199

**Comment by stefanpenner** [comment]
> @ChALkeR sounds like maybe Ember needs to add tmp to the default .npmignore that is generated?

it is, this project was likely just create after that was added

**Comment by rwwagner90** [comment]
I added it to .npmignore, so I'll close this.
