### ISSUE TITLE
copyStyles does not update on resize

### ISSUE THREAD

**Issue by davidpike7** [rwwagner90/ember-shepherd#16]
Currently the copyStyles does not update the positioning of the copied element on browser resize

**Comment by rwwagner90** [comment]
That is correct. It would be pretty intensive to copy the styles each time the browser resized. Perhaps we can do some debouncing and make something work here though.

**Comment by rwwagner90** [comment]
@davidpike7 is this issue stopping you from using ember-shepherd?

**Comment by davidpike7** [comment]
Not at all. We just simplified our CSS to remove the need to use copyStyles. Now its working great

**Comment by rwwagner90** [comment]
Okay, great. I would be open to a PR or suggestions on how to get copyStyles to be responsive, but it's not high on my priority list at this time. Would you be interested in giving it a go?

**Comment by davidpike7** [comment]
To be honest I don't think its particular high for us either now that we've got the issue sorted. 

Happy to help out elsewhere though if you're needing some help.

**Comment by rwwagner90** [comment]
Well right now we have most of the functionality and everything that we wanted to accomplish. We're always looking to make it better though, so we'd be glad to have you take a look. Any ideas for features or improvements?

**Comment by rwwagner90** [comment]
I think we'll close this in favor of people fixing styles on their end. copyStyles can be an intensive process, and recalculating it all on the fly doesn't sound like a good idea.
