### ISSUE TITLE
attachTo shouldn't be required

### ISSUE THREAD

**Issue by edborden** [rwwagner90/ember-shepherd#18]
Per the Shepherd docs, "if you don't specific an `attachTo` the element will appear in the middle of the screen."  I get `Uncaught TypeError: Cannot read property 'element' of undefined` when `attachTo` isn't defined.

**Comment by alexlafroscia** [comment]
Thanks for the report! I'll check this out this week and issue a fix!

**Comment by alexlafroscia** [comment]
@edborden can I get a full stack trace? That would be really useful.

**Comment by rwwagner90** [comment]
@edborden any chance you could throw together a small test case for us? We'd be glad to fix this.

**Comment by rwwagner90** [comment]
@alexlafroscia @edborden I had someone reach out to me directly about attachTo issues as well. Not sure if we aren't passing it correctly or is Shepherd has an issue. Check this out: https://github.com/JaroVDH/ember-shepherd-breaktest

**Comment by rwwagner90** [comment]
@alexlafroscia perhaps we need to change the way we pass attachTo? I see in that example repo that attachTo is undefined, which throws an error. Maybe we need to pass `null` instead of leaving it undefined? Not sure what Shepherd supports now.

**Comment by edborden** [comment]
I tried setting attachTo to null and got this
```
Uncaught TypeError: Cannot read property 'element' of null
_getElementFromObject @ tour.js:222
_exchangeForAttachmentConfig @ tour.js:169
(anonymous function) @ tour.js:281
(anonymous function) @ tour.js:275
ComputedPropertyPrototype.get @ ember.debug.js:14842
```

**Comment by rwwagner90** [comment]
@edborden it appears we do incorrectly handle null, but passing nothing and leaving it undefined should work, I would think. This is the code in question:

```js
 _exchangeForAttachmentConfig: function(attachTo) {
    const type = typeof attachTo;
    var config = {
      element: null,
      on: null
    };
    switch (type) {
      case "string":
      {
        config.element = this._getElementFromString(attachTo);
        const configArray = attachTo.split(' ');
        config.on = configArray[configArray.length - 1];
        break;
      }
      case "object":
      {
        config.element = this._getElementFromObject(attachTo);
        config.on = attachTo.on;
        break;
      }
      default:
        config = null;
    }
    return config;
  },
```

@alexlafroscia `typeof null` will return `"object"` so when null is passed this tries to use the object case. We need to handle passing of null probably.

**Comment by rwwagner90** [comment]
Finally got around to fixing this. Sorry for the delay!
