### ISSUE TITLE
Configuration Error

### ISSUE THREAD

**Issue by McLeanBH** [rwwagner90/ember-shepherd#2]
After running `$ ember install:addon ember-shepherd` app immediately breaks, citing the following error: (Path or pattern "bower_components/shepherd.js/shepherd.js" did not match any files), as there is no 'ember-shepherd' directory in 'bower_components'. Most other addon's I have used refer to dependency in bower.json. Emerber-shepherd directory is added to node_modules, and package.json includes shepherd dependency. Seems to be missing path for bower.  -- hope this helps, as I am eager to implement in my development.

**Comment by rwwagner90** [comment]
@McLeanBH I will check it out. I haven't actually tried installing it myself. I've just been using it in the dummy app inside the addon.

**Comment by rwwagner90** [comment]
@McLeanBH I totally forgot that I needed to include the bower dependencies in the blueprint. It should work now. Please uninstall, and install again and let me know if it works for you then.

**Comment by McLeanBH** [comment]
Just re-installed. Nothing broken, and all dependencies were added. It appears it's good to go. Thanks. Look forward to using it.

**Comment by rwwagner90** [comment]
Awesome. Glad I could help! Let me know if you encounter any other issues or feel there are some features I should implement or anything.
