### ISSUE TITLE
showCancelLink doesn't trigger 'cancel' event.

### ISSUE THREAD

**Issue by taheilo** [rwwagner90/ember-shepherd#23]
When having `showCancelLink: true` on your steps, clicking the [x] doesn't trigger the cancel event.

`this.get('tour').on('cancel', fn);`

**Comment by rwwagner90** [comment]
Thanks @taheilo. I will take a look. Totally not necessary, but if you could provide a jsbin or something, that would be helpful!

**Comment by rwwagner90** [comment]
@taheilo you just need to setup your cancel events on `tourObject`. You'll need to do something like this:

```js
      this.tour.get('tourObject').on('cancel', () => {
        console.log('cancel');
      })
```

**Comment by bekzod** [comment]
@rwwagner90 I think more logical api would be to listen to events directly on tour service object I think it should be implemented, what do you say ?

**Comment by rwwagner90** [comment]
@bekzod this seems to be something easy for the user to implement on their side. This specific issue @taheilo was saying that `this.get('tour').on('cancel', fn);` did not work, so I was just telling him how to do it correctly.

Could you elaborate on what you are thinking? It might be good to implement it, if it simplifies things for the user.

**Comment by bekzod** [comment]
instinctive approach for the user is to listen for events directly from tour object not from property of tour object (`tourObject` it is property of tour object right ?), `this.tour.on('cancel', fn);`  like @taheilo did

**Comment by rwwagner90** [comment]
@bekzod that sounds like it could be useful. If you'd like to implement it, that would be awesome :). I fixed the tests, by the way. Do you use gitter? We could chat there.

**Comment by bekzod** [comment]
cool thanks, what is gitter ? (looking it up now :) )
