### ISSUE TITLE
_this.getElementForCurrentStep()

### ISSUE THREAD

**Issue by anthonycollini** [rwwagner90/ember-shepherd#26]
I am trying to implement the add-on, but I can't get it to work properly. When I add steps to the tour, including the default next button, I get a console error when it hits `_this.getElementForCurrentStep()`:

`Uncaught TypeError: Cannot read property 'style' of null`

Any thoughts as to why?

Here are my options:

```
    this.get('tour').set('steps', [
      {
        id: 'tour-step-1',
        options: {
          title: 'Step 1 title!',
          text: ['Step 1 text.'],
          builtInButtons: [
            {
              classes: 'btn',
              text: 'Exit',
              type: 'cancel'
            },
            {
              classes: 'btn btn-success',
              text: 'Next',
              type: 'next'
            }
          ]
        }
      },

      // Step 2
      {
        id: 'tour-step-2',
        options: {
          attachTo: '.main-menu bottom',
          title: 'Step 2 title',
          text: ['Step 2 text'],
          builtInButtons: [
            {
              classes: 'btn',
              text: 'Exit',
              type: 'cancel'
            },
            {
              classes: 'btn btn-success',
              text: 'Next',
              type: 'next'
            }
          ]
        }
      }
    ]);
```

Using:
```
    "ember": "2.2.0",
    "ember-data": "2.2.1"
```

**Comment by alexlafroscia** [comment]
Is it possible to get a JSBin or Ember-Twiddle to replicate this?  I'm happy to fix the issue, it's just 1000 times easier if I have a broken example to work with.

**Comment by eguitarz** [comment]
@anthonycollini I have same error as you do, a work-around is to set `attachTo` in step1 options.

**Comment by eguitarz** [comment]
@alexlafroscia The error is raised when you did not set up `attachTo` in step options and triggering `next` or `back` event. Sometimes I don't want my `step` attach to any element... So it would be great if this can be fixed.

**Comment by rwwagner90** [comment]
@anthonycollini and @eguitarz I believe I have fixed this issue. Can you please grab v1.0.5 and try again?
