### ISSUE TITLE
Scrolls down when it doesn't need to

### ISSUE THREAD

**Issue by ryanjm** [rwwagner90/ember-shepherd#38]
I'm not sure if this is related to #35, but I don't think it is.

You can see it on the [project page](http://rwwagner90.github.io/ember-shepherd/). When you load it, it scrolls down until the element it is pointed at is at the top of the page (if your page is cached, you might need to do this in incognito).

Is there any way to disable this jumping and only scroll if the element is out of the view? Thanks!

![screen shot 2016-02-06 at 4 00 38 pm](https://cloud.githubusercontent.com/assets/90015/12870121/c973bdd4-ccea-11e5-92a6-26c8a6352eb0.png)

**Comment by rwwagner90** [comment]
@ryanjm I just turned the defaults option `scrollTo` to true for the demo.

```
 defaults: {
    classes: 'shepherd-element shepherd-open shepherd-theme-arrows',
    scrollTo: true,
    showCancelLink: true
  },
```

You can set `scrollTo` to false to stop this behavior.

**Comment by ryanjm** [comment]
Thanks @rwwagner90. I should have looked closer at that.

**Comment by rwwagner90** [comment]
No problem @ryanjm! If you were interested in some scrolling that behaves more the way you described, please feel free to make a PR. We are currently working on some scrolling issues though, so might be best to wait until we merge that in.

**Comment by rwwagner90** [comment]
@ryanjm we have merged in the new capability of using scrollTo with diasbleScroll. Please check out version 2.0.5. If you have another desired scroll behavior, we'd be happy to work with you on it. Definitely trying to get more community PRs and feature suggestions.

**Comment by ryanjm** [comment]
Thanks! I will check it out.
