### ISSUE TITLE
Doesn't support attachTo object

### ISSUE THREAD

**Issue by alexlafroscia** [rwwagner90/ember-shepherd#6]
Shepherd seems to allow you to use an object to define the `attachTo` behavior:

> For example: ".some #element left", or {element: '.some #element', on: 'left'}. If you use the object syntax, element can also be a DOM element. If you don't specify an attachTo the element will appear in the middle of the screen.

However, trying to use this with `ember-shepherd` breaks the tour with the following error

> Uncaught TypeError: currentStep.options.attachTo.split is not a function

Which corresponds to the [code found here](https://github.com/rwwagner90/ember-shepherd/blob/master/addon/components/ember-shepherd.js#L30).

**Comment by rwwagner90** [comment]
Object syntax is not supported, you are correct. I would gladly accept a PR to support it :smile:

**Comment by rwwagner90** [comment]
Should hopefully not be too difficult to fix. I can take a look, at some point, but I'm trying to build up community involvement in the project, and this would be a great one to start with. Let me know if you are interested in taking a stab at it.

**Comment by alexlafroscia** [comment]
Yeah sure, I'll see if I can put something together tonight :)

**Comment by rwwagner90** [comment]
Sounds good, thanks! For that specific split case you pointed out, you could just not split it, and use the DOM element itself, if a DOM element is passed or if a JSON object is passed, split the element property there. Shouldn't be too bad.

**Comment by rwwagner90** [comment]
@alexlafroscia did you get a chance to take a look? I'd be glad to help out if you have questions or concerns.

**Comment by alexlafroscia** [comment]
Sorry, busy few days.  I'm going to check this out tonight.

**Comment by alexlafroscia** [comment]
I keep getting an error with compilation, any ideas?  The error is

> URI is missing ')'

on

> @import url(http://fonts.googleapis.com/css?family=Roboto+Condensed:400italic,400,700|Lobster+Two:400,700);

**Comment by rwwagner90** [comment]
@alexlafroscia is that when running ember build or when does it occur? Can I assume it's not a problem anymore, since you submitted a PR?

**Comment by alexlafroscia** [comment]
Yeah, it's happening during build.  I just commented out that line, but didn't check that file in.  It seems like maybe this is [a new-ish issue in `libsass`](https://github.com/sass/libsass/issues/1096).

**Comment by rwwagner90** [comment]
Ah, well let's not worry about it then
