### ISSUE TITLE
Tagged releases?

### ISSUE THREAD

**Issue by alexlafroscia** [rwwagner90/ember-shepherd#9]
Hey, do you think it'd be a good idea to tag released? I know you're keeping up with semver, so maybe it would be good to do that as well as keep up a changelog attached to each one.

**Comment by alexlafroscia** [comment]
Maybe we should just start this as of `1.0.0`

**Comment by rwwagner90** [comment]
Yeah, let's start after 1.0. Everything was meant to be really beta until 1.0 and nothing is guaranteed.

**Comment by alexlafroscia** [comment]
Gotcha. I only just learned yesterday that technically every release can break a package before `1.0.0` according to Semver.

**Comment by rwwagner90** [comment]
Well good because we're about to break everything :smiley:

**Comment by alexlafroscia** [comment]
I was thinking the same thing haha
